### ISSUE TITLE
Feature request: keeping comments in tact

### ISSUE THREAD

**Issue by archoversight** [martinohmann/hcl-rs#112]
I am parsing HCL files that contain comments to be able to update some blocks/attributes, but I would like to keep comments in tact after parsing -> serializing back to text.

Maybe I have missed it, if so please feel free to link me to the documentation.

Thank you!

**Comment by martinohmann** [comment]
Hi! This is currently not supported and would require some bigger changes to the grammar and AST. Right now, it's using pest's magic `COMMENT` rule to match and discard them.

Maybe some lower level API for getting the full AST of an HCL document could make sense at one point. Your use case is certainly worth supporting, but it will require some work.

**Comment by archoversight** [comment]
Thanks for the response @martinohmann.

**Comment by martinohmann** [comment]
I was just checking how other projects are doing this. For example, `toml-rs` split this into a general `toml` parser with serde support and the `toml_edit` crate (which comes with its own parser) which has exactly the feature your looking for (just for TOML of course 😉 ): https://github.com/toml-rs/toml

The split might make sense for `hcl-rs` as well since editing capabilities would require a different grammar which emits tokens for every single whitespace and comment. This would probably slow down the common use case of just parsing the data and throwing away the comments and whitespace quite a bit, so it's better to keep this separate. It might be possible to reuse some code between the two of course.

I'll look a bit deeper into how `toml_edit` designed this when I have time.

**Comment by archoversight** [comment]
I'm sorry, things have been hectic at work and I haven't been able to come back to this yet. Thank you for the update and I will hopefully get some cycles to play with it in the near future!
