### ISSUE TITLE
Error when trying to parse comments starting with `//`

### ISSUE THREAD

**Issue by maxdeviant** [martinohmann/hcl-rs#188]
Despite the copious signage, I was brave (foolish?) enough to try out `hcl-edit`.

I'm happy to report that it did exactly what I wanted it to and would have been easier than the alternatives. So, thank you!

I did find one issue where `hcl-edit` doesn't correctly parse comments starting with `//`:

```
Error:    --> HCL parse error in line 112, column 51
    |
112 |   ami                  = "ami-5f6495430e7781fe5" // Ubuntu 20.04 LTS
    |                                                   ^---
    |
    = invalid expression; expected `"`, `[`, `{`, `-`, `!`, `(`, `_`, `<`, letter or digit
```

I was able to work around this for my use case by just using `#` for the comments.

**Comment by martinohmann** [comment]
Thanks for reporting this!

I overlooked an ambiguity in the grammar there. The parser treats the first `/` as a binary division operator and expects a RHS expression after it, but fails when it encounters the second `/` because it does not match any of the characters it expects for starting an expression.

I'll see if I can get this fixed later today as it should be fairly easy.

**Comment by maxdeviant** [comment]
Thanks so much for the quick turnaround!
