### ISSUE TITLE
hcl-edit: question/request - display Location from span

### ISSUE THREAD

**Issue by denfren** [martinohmann/hcl-rs#195]
I started playing with `hcl_edit` to do some parsing.

For pretty error messages I want to display the location with some context like you do with `hcl_edit::parser::error::Location`. The closest I found was - for example - `hcl_edit::structure::Block::span()` to find out where the Block is defined.

Have I overlooked a way to do this right now or should I do something alike to the Location struct?

**Comment by martinohmann** [comment]
Hi there!

To display custom error messages with location context all you need is the parser input and the span of the value of interest.

With these two you can build pretty error messages using crates like [`miette`](https://docs.rs/miette/latest/miette/) or [`ariadne`](https://docs.rs/ariadne/latest/ariadne/) which are specifically designed to do this. I don't plan to add similar functionality to `hcl-edit` because pretty errors are highly specific to your usecase. But I might think about providing some interop with one of these crates.

If you want to roll your own pretty error messages, you can have a look how it's implemented in hcl-edit internally: https://github.com/martinohmann/hcl-rs/blob/main/crates/hcl-edit/src/parser/error.rs#L57-L94. This is using the byte offset between the input and the remaining input after the parser failed though, so you will need to adjust your code to work with the start and and offset provided by the `span()` method of your value of interest.

**Comment by martinohmann** [comment]
One addition I could make to `hcl-edit` is a public helper function which creates a pair of `Location`'s from a parser input and the span, maybe with a signature like this:

```rust
fn input_location<I: AsRef<str>>(&self, input: I, span: Range<usize>) -> Option<(Location, Location)>;
```

**Comment by denfren** [comment]
I suppose we can close this. Feel free to reopen for whatever reason
