### ISSUE TITLE
Support for open vsx registry

### ISSUE THREAD

**Issue by lmtr0** [martinohmann/hcl-rs#21]
Hello there,
I use VsCodium as my editor, and it would be cool to see this extension in https://open-vsx.org/

**Comment by martinohmann** [comment]
Hi there!

I'm not familiar with VS code and its extension system, but to me it looks like a request for such a feature would be better directed to Hashicorp, since they are the creators and maintainers of the HCL language: https://github.com/hashicorp/hcl

This repo just provides a basic HCL parser written in rust which probably still fails to handle lots of edge cases in the grammar correctly. :wink:

**Comment by lmtr0** [comment]
Thx, sorry for the Inconvenience
