### ISSUE TITLE
Feature parity with go-hcl

### ISSUE THREAD

**Issue by srevinsaju** [martinohmann/hcl-rs#304]
Is hcl-rs fully feature compatible with the original HCL implementation?

**Comment by martinohmann** [comment]
Hi there @srevinsaju!

Sorry for the long wait. `hcl-rs` (or more specifically `hcl-edit`) tries to closely follow these specifications:

- https://github.com/hashicorp/hcl/blob/main/spec.md
- https://github.com/hashicorp/hcl/blob/main/hclsyntax/spec.md
- https://github.com/hashicorp/hcl/blob/main/json/spec.md

At the parser level it should support all features that go-hcl does today. However, the implementations for formatting and expression evaluation in `hcl-rs` are relatively basic at the moment. I'm planning to move formatting and expression evaluation capabilities into `hcl-edit` (which is used by `hcl-rs` under the hood and also contains the parser implementation) and would like to make them more powerful.

Another thing that is not included (yet), but might be helpful in the future is the support for HCL schemas in order to validate that a parsed HCL document only contains an allowed set of blocks with expected attributes (e.g. to enable validation that a given terraform configuration only contains well-formed `resource` and `data` blocks etc.).

Which features are interested in specifically? Maybe there's something we can do here.

**Comment by robmorgan** [comment]
@martinohmann I have a more narrow use case that is a subset of this issue.

Given the following JSON:

```json
{
    "some_attr": {
        "foo": [1, 2],
        "bar": true
    },
    "some_block": {
        "some_block_label": {
            "attr": "value"
        }
    }
}
```

I'd like to serialize it to the following HCL config:

```hcl
some_attr = {
      foo = [1, 2]
      bar = true
    }

some_block "some_block_label" {
    attr = "value"
}
```

Basically I'm trying to create a labeled block element. From what I've read and seen, this would only be possible when using a schema which is currently unsupported. Is there a way to use one of the crates to create this kind of HCL configuration or am I better off using the `builder` APIs?

Cheers

**Comment by srevinsaju** [comment]
> Sorry for the long wait. hcl-rs (or more specifically hcl-edit) tries to closely follow these specifications:
> 
>     https://github.com/hashicorp/hcl/blob/main/spec.md
>     https://github.com/hashicorp/hcl/blob/main/hclsyntax/spec.md
>     https://github.com/hashicorp/hcl/blob/main/json/spec.md

Looks like that answered my question - thank you! It would be great to drop that in the README.md

**Comment by martinohmann** [comment]
@robmorgan you can achieve this by using [`LabeledBlock`](https://docs.rs/hcl-rs/latest/hcl/ser/struct.LabeledBlock.html):

```rust
use hcl::ser::LabeledBlock;
use hcl::Value;
use indexmap::IndexMap;

#[derive(serde::Serialize)]
struct Config {
    some_attr: IndexMap<String, Value>,
    some_block: LabeledBlock<IndexMap<String, IndexMap<String, Value>>>,
}

let config = Config {
    some_attr: indexmap! {
        "foo".into() => Value::from(vec![1, 2]),
        "bar".into() => Value::from(true),
    },
    some_block: LabeledBlock::new(indexmap! {
        "some_block_label".into() => indexmap! {
            "attr".into() => Value::from("value"),
        },
    }),
};

println!("{}", hcl::to_string(&config).unwrap());
```

or via the [`labeled_block`](https://docs.rs/hcl-rs/latest/hcl/ser/fn.labeled_block.html) serializer:

```rust
use hcl::Value;
use indexmap::IndexMap;

#[derive(serde::Serialize)]
struct Config {
    some_attr: IndexMap<String, Value>,
    #[serde(serialize_with = "hcl::ser::labeled_block")]
    some_block: IndexMap<String, IndexMap<String, Value>>,
}

let config = Config {
    some_attr: indexmap! {
        "foo".into() => Value::from(vec![1, 2]),
        "bar".into() => Value::from(true),
    },
    some_block: indexmap! {
        "some_block_label".into() => indexmap! {
            "attr".into() => Value::from("value"),
        },
    },
};

println!("{}", hcl::to_string(&config).unwrap());
```

Schema support is something that I'd like to have as well, but it'll be a lot of work to implement this and I simply do not have much spare time for that at the moment.

**Comment by martinohmann** [comment]
> > Sorry for the long wait. hcl-rs (or more specifically hcl-edit) tries to closely follow these specifications:
> > ```
> > https://github.com/hashicorp/hcl/blob/main/spec.md
> > https://github.com/hashicorp/hcl/blob/main/hclsyntax/spec.md
> > https://github.com/hashicorp/hcl/blob/main/json/spec.md
> > ```
> 
> Looks like that answered my question - thank you! It would be great to drop that in the README.md

Thanks for the reminder, I'll try to add this!

**Comment by robmorgan** [comment]
@martinohmann thanks! I've been playing around with the `LabeledBlock` [example code](https://github.com/martinohmann/hcl-rs/blob/8349bdd12df96b47d5d7f0bc9ce988dc03c57fb6/crates/hcl-rs/src/ser/blocks.rs#L456) today, so I guess I was on the right track 👍
