### ISSUE TITLE
Is it possible to use raw expressions in the block macro?

### ISSUE THREAD

**Issue by mdaffin** [martinohmann/hcl-rs#57]
Using `hcl-rs = "0.6.5"` I am trying to produce the output
```hcl
module "foo" {
    name = var.name
}
```
with the block macro. But nothing I have tried can produce this output, at most it always quotes the `var.name` which is not what I need. I have tried:
```rust
    hcl::block!(
        module "foo" {
            // name = var.name // error: recursion limit reached
            name = "var.name" // Produces `name = "var.name"` (as expected)
            name = (RawExpression::new("var.name")) // Produces `name = "var.name"`
            // name = RawExpression::new("var.name") // error: recursion limit reached
        }
    )
```
And cannot see anything other way to get this to work. Is this currently possible with the macros?

Using the builder does work as expected:
```rust
    Block::builder("module")
            .add_label("foo")
            .add_attribute(("name", RawExpression::new("var.name")))
            .build()
```
But ends up being a lot noisier than the macros.

**Comment by martinohmann** [comment]
Hi there!

Coincidently, this is already fixed in `main` but not released yet. I'll most likely release `0.7.0` in the next few days.

The fix in `main` produces the block structure that you're expecting using this macro call:

```
hcl::block!(
    module "foo" {
        name = (RawExpression::new("var.name"))
    }
)
```

Using `var.name` and `name = RawExpression::new("var.name")` in the macro call will probably never be supported as it'll probably require to convert the macros into proc-macros due to the parsing complexity. These macros are just meant as convenience for simple cases, but will fall over if you try to create a more complex structure.

**Comment by mdaffin** [comment]
Yes, the main branch has fixed this. Thanks.

**Comment by martinohmann** [comment]
@mdaffin 0.7.0 was released.
